### ISSUE TITLE
Documentation for the `img-metadata.json`

### ISSUE THREAD

**Issue by alvinsj** [rburns/photolog#1]
I have successfully generated`img-metadata.json` from my set of images, but I didn't find a documentation for the fields. 

I can contribute for the docs after I figure them out.

**Comment by rburns** [comment]
currently most of them are tied to the way exiftool exposes exif properties. you can see that relationship here: https://github.com/rburns/photolog/blob/aba981f33faa57d150f92b3769bc7661dc292526/src/photolog/process/core.cljs#L18-L23

the other few are defined in the app in these functions: https://github.com/rburns/photolog/blob/aba981f33faa57d150f92b3769bc7661dc292526/src/photolog/process/core.cljs#L97-L99 

Both sets of keys could probably benefit from a bit of thought and scrutiny. 

It might be nice if the output keys and and the keys specified in the config had some congruence.  https://github.com/rburns/photolog/blob/aba981f33faa57d150f92b3769bc7661dc292526/src/photolog/process/cli.cljs#L13-L14  instead of exposing the exiftool keys there. not sure. 

worth thinking about in relation to https://github.com/rburns/photolog/issues/2#issuecomment-245197985

**Comment by rburns** [comment]
addressed here 62403575137729384025bac058d2a341d353f862
